///************************************************
/// Generated by: Huytd
/// Date: 24/04/2014 08:24:04
/// Goal: Create Form for V_DM_DON_VI
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;

using BKI_QLHT.US;
using BKI_QLHT.DS;
using BKI_QLHT.DS.CDBNames;
using BKI_QLHT.DanhMuc;

using C1.Win.C1FlexGrid;

namespace BKI_QLHT
{



	public class f103_V_DM_DON_VI : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
		private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
		internal SIS.Controls.Button.SiSButton m_cmd_delete;
		internal SIS.Controls.Button.SiSButton m_cmd_update;
		internal SIS.Controls.Button.SiSButton m_cmd_insert;
		internal SIS.Controls.Button.SiSButton m_cmd_exit;
		internal SIS.Controls.Button.SiSButton m_cmd_view;
        private Label label1;
        private ComboBox m_cbo_tk_loai_don_vi;
        private ComboBox m_cbo_tk_ma_dv_cap_tren;
        private Label label2;
        private Label label3;
        private TextBox m_txt_tim_kiem;
        private Label label4;
        internal SIS.Controls.Button.SiSButton m_cmd_tim_kiem;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label m_lbl_ten_day_du;
        private Label m_lbl_ma_viet_tat;
        private Label m_lbl_ma_so_thue;
        private Label m_lbl_loai_don_vi;
        private Label m_lbl_ma_dv_cap_tren;
        private Label m_lbl_dia_chi;
        private Label m_lbl_ghi_chu2;
        private Label m_lbl_ghi_chu3;
        private Label m_lbl_ghi_chu1;
		private System.ComponentModel.IContainer components;

		public f103_V_DM_DON_VI()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f103_V_DM_DON_VI));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_view = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.label1 = new System.Windows.Forms.Label();
            this.m_cbo_tk_loai_don_vi = new System.Windows.Forms.ComboBox();
            this.m_cbo_tk_ma_dv_cap_tren = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.m_txt_tim_kiem = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.m_cmd_tim_kiem = new SIS.Controls.Button.SiSButton();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.m_lbl_ten_day_du = new System.Windows.Forms.Label();
            this.m_lbl_ma_viet_tat = new System.Windows.Forms.Label();
            this.m_lbl_ma_so_thue = new System.Windows.Forms.Label();
            this.m_lbl_loai_don_vi = new System.Windows.Forms.Label();
            this.m_lbl_ma_dv_cap_tren = new System.Windows.Forms.Label();
            this.m_lbl_dia_chi = new System.Windows.Forms.Label();
            this.m_lbl_ghi_chu2 = new System.Windows.Forms.Label();
            this.m_lbl_ghi_chu3 = new System.Windows.Forms.Label();
            this.m_lbl_ghi_chu1 = new System.Windows.Forms.Label();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_view);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 516);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(1003, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(647, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_insert.TabIndex = 12;
            this.m_cmd_insert.Text = "&Thêm";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(735, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_update.TabIndex = 13;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_view
            // 
            this.m_cmd_view.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_view.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_view.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_view.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_view.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_view.ImageIndex = 18;
            this.m_cmd_view.ImageList = this.ImageList;
            this.m_cmd_view.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_view.Name = "m_cmd_view";
            this.m_cmd_view.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_view.TabIndex = 21;
            this.m_cmd_view.Text = "Xem";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(823, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_delete.TabIndex = 14;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(911, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Location = new System.Drawing.Point(0, 143);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(999, 203);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            this.m_fg.Click += new System.EventHandler(this.m_fg_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(390, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(156, 23);
            this.label1.TabIndex = 21;
            this.label1.Text = "Danh sách đơn vị";
            // 
            // m_cbo_tk_loai_don_vi
            // 
            this.m_cbo_tk_loai_don_vi.FormattingEnabled = true;
            this.m_cbo_tk_loai_don_vi.Location = new System.Drawing.Point(210, 50);
            this.m_cbo_tk_loai_don_vi.Name = "m_cbo_tk_loai_don_vi";
            this.m_cbo_tk_loai_don_vi.Size = new System.Drawing.Size(164, 21);
            this.m_cbo_tk_loai_don_vi.TabIndex = 22;
            // 
            // m_cbo_tk_ma_dv_cap_tren
            // 
            this.m_cbo_tk_ma_dv_cap_tren.FormattingEnabled = true;
            this.m_cbo_tk_ma_dv_cap_tren.Location = new System.Drawing.Point(547, 50);
            this.m_cbo_tk_ma_dv_cap_tren.Name = "m_cbo_tk_ma_dv_cap_tren";
            this.m_cbo_tk_ma_dv_cap_tren.Size = new System.Drawing.Size(132, 21);
            this.m_cbo_tk_ma_dv_cap_tren.TabIndex = 22;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(126, 55);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(69, 16);
            this.label2.TabIndex = 23;
            this.label2.Text = "Loại đơn vị";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(415, 55);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(114, 16);
            this.label3.TabIndex = 23;
            this.label3.Text = "Mã đơn vị cấp trên";
            // 
            // m_txt_tim_kiem
            // 
            this.m_txt_tim_kiem.Location = new System.Drawing.Point(210, 94);
            this.m_txt_tim_kiem.Name = "m_txt_tim_kiem";
            this.m_txt_tim_kiem.Size = new System.Drawing.Size(336, 20);
            this.m_txt_tim_kiem.TabIndex = 24;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(126, 94);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(61, 16);
            this.label4.TabIndex = 23;
            this.label4.Text = "Tìm kiếm";
            // 
            // m_cmd_tim_kiem
            // 
            this.m_cmd_tim_kiem.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_tim_kiem.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_tim_kiem.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_tim_kiem.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_tim_kiem.ImageIndex = 18;
            this.m_cmd_tim_kiem.ImageList = this.ImageList;
            this.m_cmd_tim_kiem.Location = new System.Drawing.Point(591, 86);
            this.m_cmd_tim_kiem.Name = "m_cmd_tim_kiem";
            this.m_cmd_tim_kiem.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_tim_kiem.TabIndex = 25;
            this.m_cmd_tim_kiem.Text = "Tìm kiếm";
            this.m_cmd_tim_kiem.Click += new System.EventHandler(this.m_cmd_tim_kiem_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(41, 425);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(77, 16);
            this.label5.TabIndex = 27;
            this.label5.Text = "Tên đầy đủ:";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(41, 395);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(73, 16);
            this.label6.TabIndex = 26;
            this.label6.Text = "Mã viết tắt:";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(41, 457);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(76, 16);
            this.label7.TabIndex = 27;
            this.label7.Text = "Mã số thuế:";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(305, 395);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(52, 16);
            this.label8.TabIndex = 26;
            this.label8.Text = "Địa chỉ:";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(305, 425);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(74, 16);
            this.label9.TabIndex = 27;
            this.label9.Text = "Loại đơn vị:";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(305, 457);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(119, 16);
            this.label10.TabIndex = 27;
            this.label10.Text = "Mã đơn vị cấp trên:";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(630, 395);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(66, 16);
            this.label11.TabIndex = 26;
            this.label11.Text = "Ghi chú 1:";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(630, 425);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(66, 16);
            this.label12.TabIndex = 27;
            this.label12.Text = "Ghi chú 2:";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(630, 457);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(66, 16);
            this.label13.TabIndex = 27;
            this.label13.Text = "Ghi chú 3:";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(390, 359);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(153, 23);
            this.label14.TabIndex = 28;
            this.label14.Text = "Thông tin chi tiết";
            // 
            // m_lbl_ten_day_du
            // 
            this.m_lbl_ten_day_du.AutoSize = true;
            this.m_lbl_ten_day_du.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ten_day_du.Location = new System.Drawing.Point(135, 425);
            this.m_lbl_ten_day_du.Name = "m_lbl_ten_day_du";
            this.m_lbl_ten_day_du.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ten_day_du.TabIndex = 26;
            this.m_lbl_ten_day_du.Text = ".....";
            // 
            // m_lbl_ma_viet_tat
            // 
            this.m_lbl_ma_viet_tat.AutoSize = true;
            this.m_lbl_ma_viet_tat.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ma_viet_tat.Location = new System.Drawing.Point(135, 395);
            this.m_lbl_ma_viet_tat.Name = "m_lbl_ma_viet_tat";
            this.m_lbl_ma_viet_tat.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ma_viet_tat.TabIndex = 26;
            this.m_lbl_ma_viet_tat.Text = ".....";
            // 
            // m_lbl_ma_so_thue
            // 
            this.m_lbl_ma_so_thue.AutoSize = true;
            this.m_lbl_ma_so_thue.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ma_so_thue.Location = new System.Drawing.Point(135, 457);
            this.m_lbl_ma_so_thue.Name = "m_lbl_ma_so_thue";
            this.m_lbl_ma_so_thue.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ma_so_thue.TabIndex = 26;
            this.m_lbl_ma_so_thue.Text = ".....";
            // 
            // m_lbl_loai_don_vi
            // 
            this.m_lbl_loai_don_vi.AutoSize = true;
            this.m_lbl_loai_don_vi.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_loai_don_vi.Location = new System.Drawing.Point(433, 425);
            this.m_lbl_loai_don_vi.Name = "m_lbl_loai_don_vi";
            this.m_lbl_loai_don_vi.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_loai_don_vi.TabIndex = 26;
            this.m_lbl_loai_don_vi.Text = ".....";
            // 
            // m_lbl_ma_dv_cap_tren
            // 
            this.m_lbl_ma_dv_cap_tren.AutoSize = true;
            this.m_lbl_ma_dv_cap_tren.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ma_dv_cap_tren.Location = new System.Drawing.Point(433, 457);
            this.m_lbl_ma_dv_cap_tren.Name = "m_lbl_ma_dv_cap_tren";
            this.m_lbl_ma_dv_cap_tren.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ma_dv_cap_tren.TabIndex = 26;
            this.m_lbl_ma_dv_cap_tren.Text = ".....";
            // 
            // m_lbl_dia_chi
            // 
            this.m_lbl_dia_chi.AutoSize = true;
            this.m_lbl_dia_chi.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_dia_chi.Location = new System.Drawing.Point(433, 395);
            this.m_lbl_dia_chi.Name = "m_lbl_dia_chi";
            this.m_lbl_dia_chi.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_dia_chi.TabIndex = 26;
            this.m_lbl_dia_chi.Text = ".....";
            // 
            // m_lbl_ghi_chu2
            // 
            this.m_lbl_ghi_chu2.AutoSize = true;
            this.m_lbl_ghi_chu2.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ghi_chu2.Location = new System.Drawing.Point(719, 425);
            this.m_lbl_ghi_chu2.Name = "m_lbl_ghi_chu2";
            this.m_lbl_ghi_chu2.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ghi_chu2.TabIndex = 26;
            this.m_lbl_ghi_chu2.Text = ".....";
            // 
            // m_lbl_ghi_chu3
            // 
            this.m_lbl_ghi_chu3.AutoSize = true;
            this.m_lbl_ghi_chu3.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ghi_chu3.Location = new System.Drawing.Point(719, 457);
            this.m_lbl_ghi_chu3.Name = "m_lbl_ghi_chu3";
            this.m_lbl_ghi_chu3.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ghi_chu3.TabIndex = 26;
            this.m_lbl_ghi_chu3.Text = ".....";
            // 
            // m_lbl_ghi_chu1
            // 
            this.m_lbl_ghi_chu1.AutoSize = true;
            this.m_lbl_ghi_chu1.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ghi_chu1.Location = new System.Drawing.Point(719, 395);
            this.m_lbl_ghi_chu1.Name = "m_lbl_ghi_chu1";
            this.m_lbl_ghi_chu1.Size = new System.Drawing.Size(28, 16);
            this.m_lbl_ghi_chu1.TabIndex = 26;
            this.m_lbl_ghi_chu1.Text = ".....";
            // 
            // f103_V_DM_DON_VI
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(1003, 552);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.m_lbl_ghi_chu1);
            this.Controls.Add(this.m_lbl_ghi_chu3);
            this.Controls.Add(this.m_lbl_dia_chi);
            this.Controls.Add(this.m_lbl_ma_dv_cap_tren);
            this.Controls.Add(this.m_lbl_ghi_chu2);
            this.Controls.Add(this.m_lbl_ma_viet_tat);
            this.Controls.Add(this.m_lbl_loai_don_vi);
            this.Controls.Add(this.m_lbl_ma_so_thue);
            this.Controls.Add(this.m_lbl_ten_day_du);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.m_cmd_tim_kiem);
            this.Controls.Add(this.m_txt_tim_kiem);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.m_cbo_tk_ma_dv_cap_tren);
            this.Controls.Add(this.m_cbo_tk_loai_don_vi);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f103_V_DM_DON_VI";
            this.Text = "f103_V_DM_DON_VI";
            this.Load += new System.EventHandler(this.f103_V_DM_DON_VI_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
			MA_SO_THUE = 3
,GHI_CHU_1 = 12
,ID = 15
,GHI_CHU_3 = 14
,ID_DV_CAP_TREN = 10
,GHI_CHU_2 = 13
,MA_VIET_TAT_DV_CAP_TREN = 11
,TEN_DAY_DU = 2
,MA_VIET_TAT = 1
,TEN = 9
,ID_LOAI_TU_DIEN = 8
,DIA_CHI = 4
,ID_DON_VI_CAP_TREN = 5
,ID_LOAI_DON_VI = 6
,ID_TU_DIEN = 7

		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_V_DM_DON_VI m_ds_v_dm_don_vi = new DS_V_DM_DON_VI();
		US_V_DM_DON_VI m_us_v_dm_don_vi = new US_V_DM_DON_VI();
        US_DM_DON_VI m_us_dm_don_vi = new US_DM_DON_VI();
        DS_DM_DON_VI m_ds_dm_don_vi = new DS_DM_DON_VI();
		#endregion

		#region Private Methods
		private void format_controls(){
			CControlFormat.setFormStyle(this);
			CControlFormat.setC1FlexFormat(m_fg);
			set_define_events();
			this.KeyPreview = true;		
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);
			load_data_2_grid();		
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(V_DM_DON_VI.MA_SO_THUE, e_col_Number.MA_SO_THUE);
			v_htb.Add(V_DM_DON_VI.GHI_CHU_1, e_col_Number.GHI_CHU_1);
			v_htb.Add(V_DM_DON_VI.ID, e_col_Number.ID);
			v_htb.Add(V_DM_DON_VI.GHI_CHU_3, e_col_Number.GHI_CHU_3);
			v_htb.Add(V_DM_DON_VI.ID_DV_CAP_TREN, e_col_Number.ID_DV_CAP_TREN);
			v_htb.Add(V_DM_DON_VI.GHI_CHU_2, e_col_Number.GHI_CHU_2);
			v_htb.Add(V_DM_DON_VI.MA_VIET_TAT_DV_CAP_TREN, e_col_Number.MA_VIET_TAT_DV_CAP_TREN);
			v_htb.Add(V_DM_DON_VI.TEN_DAY_DU, e_col_Number.TEN_DAY_DU);
			v_htb.Add(V_DM_DON_VI.MA_VIET_TAT, e_col_Number.MA_VIET_TAT);
			v_htb.Add(V_DM_DON_VI.TEN, e_col_Number.TEN);
			v_htb.Add(V_DM_DON_VI.ID_LOAI_TU_DIEN, e_col_Number.ID_LOAI_TU_DIEN);
			v_htb.Add(V_DM_DON_VI.DIA_CHI, e_col_Number.DIA_CHI);
			v_htb.Add(V_DM_DON_VI.ID_DON_VI_CAP_TREN, e_col_Number.ID_DON_VI_CAP_TREN);
			v_htb.Add(V_DM_DON_VI.ID_LOAI_DON_VI, e_col_Number.ID_LOAI_DON_VI);
			v_htb.Add(V_DM_DON_VI.ID_TU_DIEN, e_col_Number.ID_TU_DIEN);
									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds_v_dm_don_vi.V_DM_DON_VI.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){						
			m_ds_v_dm_don_vi = new DS_V_DM_DON_VI();			
			m_us_v_dm_don_vi.FillDataset(m_ds_v_dm_don_vi);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds_v_dm_don_vi, m_fg, m_obj_trans);
			m_fg.Redraw = true;
		}
		private void grid2us_object(US_DM_DON_VI i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}
        private void v_grid2us_object(US_V_DM_DON_VI i_us
            , int i_grid_row)
        {
            DataRow v_dr;
            v_dr = (DataRow)m_fg.Rows[i_grid_row].UserData;
            m_obj_trans.GridRow2DataRow(i_grid_row, v_dr);
            i_us.DataRow2Me(v_dr);
        }

	
		private void us_object2grid(US_V_DM_DON_VI i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}


		private void insert_v_dm_don_vi(){
            f103_v_dm_don_vi_de  v_fDE = new f103_v_dm_don_vi_de();
            v_fDE.display_for_insert();
			load_data_2_grid();
		}

		private void update_v_dm_don_vi(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us_dm_don_vi, m_fg.Row);
            f103_v_dm_don_vi_de v_fDE = new f103_v_dm_don_vi_de();
            v_fDE.display_for_update(m_us_dm_don_vi);
			load_data_2_grid();
		}
				
		private void delete_v_dm_don_vi(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_DM_DON_VI v_us = new US_DM_DON_VI();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_v_dm_don_vi(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us_dm_don_vi, m_fg.Row);
		//	f103_V_DM_DON_VI_DE v_fDE = new f103_V_DM_DON_VI_DE();			
		//	v_fDE.display(m_us);
		}
		private void set_define_events(){
			m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
			m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
			m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
			m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
			m_cmd_view.Click += new EventHandler(m_cmd_view_Click);
		}
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
		private void f103_V_DM_DON_VI_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
                load_data_2_cbo_tk_loai_don_vi();
                load_data_2_cbo_tk_ma_dv_cap_tren();
                load_thong_tin_chi_tiet();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

        private void load_thong_tin_chi_tiet()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            v_grid2us_object(m_us_v_dm_don_vi, m_fg.Row);
            m_lbl_ma_viet_tat.Text = m_us_v_dm_don_vi.strMA_VIET_TAT;
            m_lbl_ten_day_du.Text = m_us_v_dm_don_vi.strTEN_DAY_DU;
            m_lbl_ma_so_thue.Text = m_us_v_dm_don_vi.strMA_SO_THUE;
            m_lbl_ma_dv_cap_tren.Text = m_us_v_dm_don_vi.strMA_VIET_TAT_DV_CAP_TREN;
            m_lbl_dia_chi.Text = m_us_v_dm_don_vi.strDIA_CHI;
            m_lbl_loai_don_vi.Text = m_us_v_dm_don_vi.strTEN;
            m_lbl_ghi_chu1.Text = m_us_v_dm_don_vi.strGHI_CHU_1;
            m_lbl_ghi_chu2.Text = m_us_v_dm_don_vi.strGHI_CHU_2;
            m_lbl_ghi_chu3.Text = m_us_v_dm_don_vi.strGHI_CHU_3;
        }

        private void load_data_2_cbo_tk_ma_dv_cap_tren()
        {
            US_DM_DON_VI v_us = new US_DM_DON_VI();
            DS_DM_DON_VI v_ds = new DS_DM_DON_VI();
            v_us.FillDataset(v_ds);
            m_cbo_tk_ma_dv_cap_tren.DataSource = v_ds.DM_DON_VI;
            m_cbo_tk_ma_dv_cap_tren.ValueMember = DM_DON_VI.ID_DON_VI_CAP_TREN;
            m_cbo_tk_ma_dv_cap_tren.DisplayMember = DM_DON_VI.MA_VIET_TAT;
        }

        private void load_data_2_cbo_tk_loai_don_vi()
        {
            US_CM_DM_TU_DIEN v_us = new US_CM_DM_TU_DIEN();
            DS_CM_DM_TU_DIEN v_ds = new DS_CM_DM_TU_DIEN();
            v_us.FillDatasetByIdLoaiTuDien(v_ds,4);
            m_cbo_tk_loai_don_vi.DataSource = v_ds.CM_DM_TU_DIEN;
            m_cbo_tk_loai_don_vi.ValueMember = CM_DM_TU_DIEN.ID;
            m_cbo_tk_loai_don_vi.DisplayMember = CM_DM_TU_DIEN.TEN;
        }


		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
				insert_v_dm_don_vi();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
				update_v_dm_don_vi();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_v_dm_don_vi();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_view_Click(object sender, EventArgs e) {
			try{
				view_v_dm_don_vi();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

        private void m_fg_Click(object sender, EventArgs e)
        {
            load_thong_tin_chi_tiet();
        }

        private void m_cmd_tim_kiem_Click(object sender, EventArgs e)
        {
            string v_tu_khoa = m_txt_tim_kiem.Text.Trim();
            decimal v_ip_cbo_loai_don_vi = Convert.ToDecimal(m_cbo_tk_loai_don_vi.SelectedValue);
            decimal v_ip_cbo_ma_dv_cap_tren = Convert.ToDecimal(m_cbo_tk_ma_dv_cap_tren.SelectedValue);
            US_V_DM_DON_VI v_us_v_dm_don_vi = new US_V_DM_DON_VI();
            DS_V_DM_DON_VI v_ds_v_dm_don_vi = new DS_V_DM_DON_VI();
            v_us_v_dm_don_vi.FillDatasetSearch(v_ds_v_dm_don_vi, v_tu_khoa, v_ip_cbo_loai_don_vi, v_ip_cbo_ma_dv_cap_tren);
            m_fg.Redraw = false;
            CGridUtils.Dataset2C1Grid(v_ds_v_dm_don_vi, m_fg, m_obj_trans);
            m_fg.Redraw = true;
        }

	}
}

