Imports IP.Core.IPData

'''************************************************
''' Generated by: TuDM
''' Date: 24/05/2014 09:29:21
''' Goal: Create User Service Class for V_HT_PHAN_QUYEN
'''************************************************
''' <summary>
''' Create User Service Class for V_HT_PHAN_QUYEN
''' </summary>

Imports IP.Core.IPCommon
Imports IP.Core.IPUserService
Imports System.Data.SqlClient
Imports System.Data


Public Class US_V_HT_PHAN_QUYEN
    Inherits US_Object
    Private Const c_TableName As String = "V_HT_PHAN_QUYEN"
#Region "Public Properties"
    Public Property dcID() As Decimal
        Get
            Return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal)
        End Get
        Set(value As Decimal)
            pm_objDR("ID") = value
        End Set
    End Property

    Public Function IsIDNull() As Boolean
        Return pm_objDR.IsNull("ID")
    End Function

    Public Sub SetIDNull()
        pm_objDR("ID") = System.Convert.DBNull
    End Sub

    Public Property dcID_FORM() As Decimal
        Get
            Return CNull.RowNVLDecimal(pm_objDR, "ID_FORM", IPConstants.c_DefaultDecimal)
        End Get
        Set(value As Decimal)
            pm_objDR("ID_FORM") = value
        End Set
    End Property

    Public Function IsID_FORMNull() As Boolean
        Return pm_objDR.IsNull("ID_FORM")
    End Function

    Public Sub SetID_FORMNull()
        pm_objDR("ID_FORM") = System.Convert.DBNull
    End Sub

    Public Property strCONTROL_NAME() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "CONTROL_NAME", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("CONTROL_NAME") = value
        End Set
    End Property

    Public Function IsCONTROL_NAMENull() As Boolean
        Return pm_objDR.IsNull("CONTROL_NAME")
    End Function

    Public Sub SetCONTROL_NAMENull()
        pm_objDR("CONTROL_NAME") = System.Convert.DBNull
    End Sub

    Public Property strCONTROL_TYPE() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "CONTROL_TYPE", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("CONTROL_TYPE") = value
        End Set
    End Property

    Public Function IsCONTROL_TYPENull() As Boolean
        Return pm_objDR.IsNull("CONTROL_TYPE")
    End Function

    Public Sub SetCONTROL_TYPENull()
        pm_objDR("CONTROL_TYPE") = System.Convert.DBNull
    End Sub

    Public Property strCONTROL_DISPLAY() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "CONTROL_DISPLAY", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("CONTROL_DISPLAY") = value
        End Set
    End Property

    Public Function IsCONTROL_DISPLAYNull() As Boolean
        Return pm_objDR.IsNull("CONTROL_DISPLAY")
    End Function

    Public Sub SetCONTROL_DISPLAYNull()
        pm_objDR("CONTROL_DISPLAY") = System.Convert.DBNull
    End Sub

    Public Property strCONTROL_TEXT() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "CONTROL_TEXT", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("CONTROL_TEXT") = value
        End Set
    End Property

    Public Function IsCONTROL_TEXTNull() As Boolean
        Return pm_objDR.IsNull("CONTROL_TEXT")
    End Function

    Public Sub SetCONTROL_TEXTNull()
        pm_objDR("CONTROL_TEXT") = System.Convert.DBNull
    End Sub

    Public Property strFORM_NAME() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "FORM_NAME", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("FORM_NAME") = value
        End Set
    End Property

    Public Function IsFORM_NAMENull() As Boolean
        Return pm_objDR.IsNull("FORM_NAME")
    End Function

    Public Sub SetFORM_NAMENull()
        pm_objDR("FORM_NAME") = System.Convert.DBNull
    End Sub

    Public Property strDISPLAY_NAME() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "DISPLAY_NAME", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("DISPLAY_NAME") = value
        End Set
    End Property

    Public Function IsDISPLAY_NAMENull() As Boolean
        Return pm_objDR.IsNull("DISPLAY_NAME")
    End Function

    Public Sub SetDISPLAY_NAMENull()
        pm_objDR("DISPLAY_NAME") = System.Convert.DBNull
    End Sub

    Public Property strMENU_ITEM_NAME() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "MENU_ITEM_NAME", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("MENU_ITEM_NAME") = value
        End Set
    End Property

    Public Function IsMENU_ITEM_NAMENull() As Boolean
        Return pm_objDR.IsNull("MENU_ITEM_NAME")
    End Function

    Public Sub SetMENU_ITEM_NAMENull()
        pm_objDR("MENU_ITEM_NAME") = System.Convert.DBNull
    End Sub

    Public Property dcID_USER_GROUP() As Decimal
        Get
            Return CNull.RowNVLDecimal(pm_objDR, "ID_USER_GROUP", IPConstants.c_DefaultDecimal)
        End Get
        Set(value As Decimal)
            pm_objDR("ID_USER_GROUP") = value
        End Set
    End Property

    Public Function IsID_USER_GROUPNull() As Boolean
        Return pm_objDR.IsNull("ID_USER_GROUP")
    End Function

    Public Sub SetID_USER_GROUPNull()
        pm_objDR("ID_USER_GROUP") = System.Convert.DBNull
    End Sub

    Public Property dcID_QUYEN() As Decimal
        Get
            Return CNull.RowNVLDecimal(pm_objDR, "ID_QUYEN", IPConstants.c_DefaultDecimal)
        End Get
        Set(value As Decimal)
            pm_objDR("ID_QUYEN") = value
        End Set
    End Property

    Public Function IsID_QUYENNull() As Boolean
        Return pm_objDR.IsNull("ID_QUYEN")
    End Function

    Public Sub SetID_QUYENNull()
        pm_objDR("ID_QUYEN") = System.Convert.DBNull
    End Sub

    Public Property strUSER_GROUP_NAME() As String
        Get
            Return CNull.RowNVLString(pm_objDR, "USER_GROUP_NAME", IPConstants.c_DefaultString)
        End Get
        Set(value As String)
            pm_objDR("USER_GROUP_NAME") = value
        End Set
    End Property

    Public Function IsUSER_GROUP_NAMENull() As Boolean
        Return pm_objDR.IsNull("USER_GROUP_NAME")
    End Function

    Public Sub SetUSER_GROUP_NAMENull()
        pm_objDR("USER_GROUP_NAME") = System.Convert.DBNull
    End Sub

#End Region
#Region "Init Functions"
    Public Sub New()
        pm_objDS = New DS_V_HT_PHAN_QUYEN()
        pm_strTableName = c_TableName
        pm_objDR = pm_objDS.Tables(pm_strTableName).NewRow()
    End Sub

    Public Sub New(i_objDR As DataRow)
        Me.New()
        Me.DataRow2Me(i_objDR)
    End Sub

    Public Sub New(i_dbID As Decimal)
        pm_objDS = New DS_V_HT_PHAN_QUYEN()
        pm_strTableName = c_TableName
        Dim v_objMkCmd As IMakeSelectCmd = New CMakeAndSelectCmd(pm_objDS, c_TableName)
        v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang)
        Dim v_cmdSQL As SqlCommand
        v_cmdSQL = v_objMkCmd.getSelectCmd()
        Me.FillDatasetByCommand(pm_objDS, v_cmdSQL)
        pm_objDR = getRowClone(pm_objDS.Tables(pm_strTableName).Rows(0))
    End Sub
#End Region
End Class