///************************************************
/// Generated by: DungNT
/// Date: 31/03/2014 02:42:52
/// Goal: Create User Service Class for GD_CT_KHUYEN_MAI
///************************************************
/// <summary>
/// Create User Service Class for GD_CT_KHUYEN_MAI
/// </summary>

using System;
using BKI_QLHT.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLHT.US{

public class US_GD_CT_KHUYEN_MAI : US_Object
{
	private const string c_TableName = "GD_CT_KHUYEN_MAI";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strTEN_CT_KHUYEN_MAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_CT_KHUYEN_MAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_CT_KHUYEN_MAI"] = value;
		}
	}

	public bool IsTEN_CT_KHUYEN_MAINull() 
	{
		return pm_objDR.IsNull("TEN_CT_KHUYEN_MAI");
	}

	public void SetTEN_CT_KHUYEN_MAINull() {
		pm_objDR["TEN_CT_KHUYEN_MAI"] = System.Convert.DBNull;
	}

	public string strMA_CT_KHUYEN_MAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_CT_KHUYEN_MAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_CT_KHUYEN_MAI"] = value;
		}
	}

	public bool IsMA_CT_KHUYEN_MAINull() 
	{
		return pm_objDR.IsNull("MA_CT_KHUYEN_MAI");
	}

	public void SetMA_CT_KHUYEN_MAINull() {
		pm_objDR["MA_CT_KHUYEN_MAI"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_KET_THUC
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_KET_THUC", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_KET_THUC"] = value;
		}
	}

	public bool IsNGAY_KET_THUCNull()
	{
		return pm_objDR.IsNull("NGAY_KET_THUC");
	}

	public void SetNGAY_KET_THUCNull()
	{
		pm_objDR["NGAY_KET_THUC"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_BAT_DAU
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_BAT_DAU", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_BAT_DAU"] = value;
		}
	}

	public bool IsNGAY_BAT_DAUNull()
	{
		return pm_objDR.IsNull("NGAY_BAT_DAU");
	}

	public void SetNGAY_BAT_DAUNull()
	{
		pm_objDR["NGAY_BAT_DAU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_CT_KHUYEN_MAI() 
	{
		pm_objDS = new DS_GD_CT_KHUYEN_MAI();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_CT_KHUYEN_MAI(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_CT_KHUYEN_MAI(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_CT_KHUYEN_MAI();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
