///************************************************
/// Generated by: DungNT
/// Date: 31/03/2014 02:43:48
/// Goal: Create User Service Class for GD_CT_KHUYEN_MAI_DT
///************************************************
/// <summary>
/// Create User Service Class for GD_CT_KHUYEN_MAI_DT
/// </summary>

using System;
using BKI_QLHT.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLHT.US{

public class US_GD_CT_KHUYEN_MAI_DT : US_Object
{
	private const string c_TableName = "GD_CT_KHUYEN_MAI_DT";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_DOI_TUONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DOI_TUONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DOI_TUONG"] = value;
		}
	}

	public bool IsID_DOI_TUONGNull()	{
		return pm_objDR.IsNull("ID_DOI_TUONG");
	}

	public void SetID_DOI_TUONGNull() {
		pm_objDR["ID_DOI_TUONG"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

	public decimal dcID_CT_KHUYEN_MAI_DETAIL 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_CT_KHUYEN_MAI_DETAIL", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_CT_KHUYEN_MAI_DETAIL"] = value;
		}
	}

	public bool IsID_CT_KHUYEN_MAI_DETAILNull()	{
		return pm_objDR.IsNull("ID_CT_KHUYEN_MAI_DETAIL");
	}

	public void SetID_CT_KHUYEN_MAI_DETAILNull() {
		pm_objDR["ID_CT_KHUYEN_MAI_DETAIL"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_CT_KHUYEN_MAI_DT() 
	{
		pm_objDS = new DS_GD_CT_KHUYEN_MAI_DT();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_CT_KHUYEN_MAI_DT(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_CT_KHUYEN_MAI_DT(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_CT_KHUYEN_MAI_DT();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
