///************************************************
/// Generated by: HuyTD
/// Date: 02/05/2014 10:13:42
/// Goal: Create User Service Class for V_GD_GIAO_DICH_DETAIL
///************************************************
/// <summary>
/// Create User Service Class for V_GD_GIAO_DICH_DETAIL
/// </summary>

using System;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;


namespace BKI_QLHT.US{

public class US_V_GD_GIAO_DICH_DETAIL : US_Object
{
	private const string c_TableName = "V_GD_GIAO_DICH_DETAIL";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_GIAO_DICH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GIAO_DICH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GIAO_DICH"] = value;
		}
	}

	public bool IsID_GIAO_DICHNull()	{
		return pm_objDR.IsNull("ID_GIAO_DICH");
	}

	public void SetID_GIAO_DICHNull() {
		pm_objDR["ID_GIAO_DICH"] = System.Convert.DBNull;
	}

	public decimal dcID_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_THUOC"] = value;
		}
	}

	public bool IsID_THUOCNull()	{
		return pm_objDR.IsNull("ID_THUOC");
	}

	public void SetID_THUOCNull() {
		pm_objDR["ID_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_THUOC"] = value;
		}
	}

	public bool IsID_DON_VI_THUOCNull()	{
		return pm_objDR.IsNull("ID_DON_VI_THUOC");
	}

	public void SetID_DON_VI_THUOCNull() {
		pm_objDR["ID_DON_VI_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG"] = value;
		}
	}

	public bool IsSO_LUONGNull()	{
		return pm_objDR.IsNull("SO_LUONG");
	}

	public void SetSO_LUONGNull() {
		pm_objDR["SO_LUONG"] = System.Convert.DBNull;
	}

	public decimal dcID_NHA_CUNG_CAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHA_CUNG_CAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHA_CUNG_CAP"] = value;
		}
	}

	public bool IsID_NHA_CUNG_CAPNull()	{
		return pm_objDR.IsNull("ID_NHA_CUNG_CAP");
	}

	public void SetID_NHA_CUNG_CAPNull() {
		pm_objDR["ID_NHA_CUNG_CAP"] = System.Convert.DBNull;
	}

	public decimal dcID_NUOC_SX 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NUOC_SX", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NUOC_SX"] = value;
		}
	}

	public bool IsID_NUOC_SXNull()	{
		return pm_objDR.IsNull("ID_NUOC_SX");
	}

	public void SetID_NUOC_SXNull() {
		pm_objDR["ID_NUOC_SX"] = System.Convert.DBNull;
	}

	public decimal dcID_HANG_SX 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_HANG_SX", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_HANG_SX"] = value;
		}
	}

	public bool IsID_HANG_SXNull()	{
		return pm_objDR.IsNull("ID_HANG_SX");
	}

	public void SetID_HANG_SXNull() {
		pm_objDR["ID_HANG_SX"] = System.Convert.DBNull;
	}

	public DateTime datHAN_SU_DUNG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "HAN_SU_DUNG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["HAN_SU_DUNG"] = value;
		}
	}

	public bool IsHAN_SU_DUNGNull()
	{
		return pm_objDR.IsNull("HAN_SU_DUNG");
	}

	public void SetHAN_SU_DUNGNull()
	{
		pm_objDR["HAN_SU_DUNG"] = System.Convert.DBNull;
	}

	public decimal dcGIA 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA"] = value;
		}
	}

	public bool IsGIANull()	{
		return pm_objDR.IsNull("GIA");
	}

	public void SetGIANull() {
		pm_objDR["GIA"] = System.Convert.DBNull;
	}

	public decimal dcID_V_DM_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_V_DM_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_V_DM_THUOC"] = value;
		}
	}

	public bool IsID_V_DM_THUOCNull()	{
		return pm_objDR.IsNull("ID_V_DM_THUOC");
	}

	public void SetID_V_DM_THUOCNull() {
		pm_objDR["ID_V_DM_THUOC"] = System.Convert.DBNull;
	}

	public string strDISPLAY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DISPLAY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DISPLAY"] = value;
		}
	}

	public bool IsDISPLAYNull() 
	{
		return pm_objDR.IsNull("DISPLAY");
	}

	public void SetDISPLAYNull() {
		pm_objDR["DISPLAY"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_TINH_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_TINH_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_TINH_THUOC"] = value;
		}
	}

	public bool IsID_DON_VI_TINH_THUOCNull()	{
		return pm_objDR.IsNull("ID_DON_VI_TINH_THUOC");
	}

	public void SetID_DON_VI_TINH_THUOCNull() {
		pm_objDR["ID_DON_VI_TINH_THUOC"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public decimal dcGD_GIA_BAN_ID_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GD_GIA_BAN_ID_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GD_GIA_BAN_ID_THUOC"] = value;
		}
	}

	public bool IsGD_GIA_BAN_ID_THUOCNull()	{
		return pm_objDR.IsNull("GD_GIA_BAN_ID_THUOC");
	}

	public void SetGD_GIA_BAN_ID_THUOCNull() {
		pm_objDR["GD_GIA_BAN_ID_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcGIA_BAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA_BAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA_BAN"] = value;
		}
	}

	public bool IsGIA_BANNull()	{
		return pm_objDR.IsNull("GIA_BAN");
	}

	public void SetGIA_BANNull() {
		pm_objDR["GIA_BAN"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_TINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_TINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_TINH"] = value;
		}
	}

	public bool IsID_DON_VI_TINHNull()	{
		return pm_objDR.IsNull("ID_DON_VI_TINH");
	}

	public void SetID_DON_VI_TINHNull() {
		pm_objDR["ID_DON_VI_TINH"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_GD_GIAO_DICH_DETAIL() 
	{
		pm_objDS = new DS_V_GD_GIAO_DICH_DETAIL();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_GD_GIAO_DICH_DETAIL(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_GD_GIAO_DICH_DETAIL(decimal i_dbID) 
	{
		pm_objDS = new DS_V_GD_GIAO_DICH_DETAIL();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
