///************************************************
/// Generated by: TuNA
/// Date: 30-04-2014 11:53:14
/// Goal: Create User Service Class for V_DM_NSX
///************************************************
/// <summary>
/// Create User Service Class for V_DM_NSX
/// </summary>

using System;
using WebDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_V_DM_NSX : US_Object
{
	private const string c_TableName = "V_DM_NSX";
#region "Public Properties"
	public decimal dcID_LOAI_DM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_DM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_DM"] = value;
		}
	}

	public bool IsID_LOAI_DMNull()	{
		return pm_objDR.IsNull("ID_LOAI_DM");
	}

	public void SetID_LOAI_DMNull() {
		pm_objDR["ID_LOAI_DM"] = System.Convert.DBNull;
	}

	public string strTEN_NUOCSX 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NUOCSX", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NUOCSX"] = value;
		}
	}

	public bool IsTEN_NUOCSXNull() 
	{
		return pm_objDR.IsNull("TEN_NUOCSX");
	}

	public void SetTEN_NUOCSXNull() {
		pm_objDR["TEN_NUOCSX"] = System.Convert.DBNull;
	}

	public string strMA_NUOCSX 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_NUOCSX", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_NUOCSX"] = value;
		}
	}

	public bool IsMA_NUOCSXNull() 
	{
		return pm_objDR.IsNull("MA_NUOCSX");
	}

	public void SetMA_NUOCSXNull() {
		pm_objDR["MA_NUOCSX"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DM_NSX() 
	{
		pm_objDS = new DS_V_DM_NSX();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_NSX(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_NSX(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_NSX();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
