///************************************************
/// Generated by: VinhNQ
/// Date: 02/05/2014 05:35:46
/// Goal: Create User Service Class for V_HAN_SU_DUNG
///************************************************
/// <summary>
/// Create User Service Class for V_HAN_SU_DUNG
/// </summary>

using System;
using BKI_QLHT.DS;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;


namespace BKI_QLHT{

public class US_V_HAN_SU_DUNG : US_Object
{
	private const string c_TableName = "V_HAN_SU_DUNG";
    #region "Public Properties"
    public string strTEN_THUOC
    {
        get
        {
            return CNull.RowNVLString(pm_objDR, "TEN_THUOC", IPConstants.c_DefaultString);
        }
        set
        {
            pm_objDR["TEN_THUOC"] = value;
        }
    }

    public bool IsTEN_THUOCNull()
    {
        return pm_objDR.IsNull("TEN_THUOC");
    }

    public void SetTEN_THUOCNull()
    {
        pm_objDR["TEN_THUOC"] = System.Convert.DBNull;
    }

    public string strHAN_SD
    {
        get
        {
            return CNull.RowNVLString(pm_objDR, "HAN_SD", IPConstants.c_DefaultString);
        }
        set
        {
            pm_objDR["HAN_SD"] = value;
        }
    }

    public bool IsHAN_SDNull()
    {
        return pm_objDR.IsNull("HAN_SD");
    }

    public void SetHAN_SDNull()
    {
        pm_objDR["HAN_SD"] = System.Convert.DBNull;
    }

    public decimal dcSO_DU
    {
        get
        {
            return CNull.RowNVLDecimal(pm_objDR, "SO_DU", IPConstants.c_DefaultDecimal);
        }
        set
        {
            pm_objDR["SO_DU"] = value;
        }
    }

    public bool IsSO_DUNull()
    {
        return pm_objDR.IsNull("SO_DU");
    }

    public void SetSO_DUNull()
    {
        pm_objDR["SO_DU"] = System.Convert.DBNull;
    }

    public string strTEN_DON_VI
    {
        get
        {
            return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
        }
        set
        {
            pm_objDR["TEN_DON_VI"] = value;
        }
    }

    public bool IsTEN_DON_VINull()
    {
        return pm_objDR.IsNull("TEN_DON_VI");
    }

    public void SetTEN_DON_VINull()
    {
        pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
    }

    public string strMA_GIAO_DICH
    {
        get
        {
            return CNull.RowNVLString(pm_objDR, "MA_GIAO_DICH", IPConstants.c_DefaultString);
        }
        set
        {
            pm_objDR["MA_GIAO_DICH"] = value;
        }
    }

    public bool IsMA_GIAO_DICHNull()
    {
        return pm_objDR.IsNull("MA_GIAO_DICH");
    }

    public void SetMA_GIAO_DICHNull()
    {
        pm_objDR["MA_GIAO_DICH"] = System.Convert.DBNull;
    }

    #endregion
    #region "Init Functions"
    public US_V_HAN_SU_DUNG()
    {
        pm_objDS = new DS_V_HAN_SU_DUNG();
        pm_strTableName = c_TableName;
        pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
    }

    public US_V_HAN_SU_DUNG(DataRow i_objDR)
        : this()
    {
        this.DataRow2Me(i_objDR);
    }

    public US_V_HAN_SU_DUNG(decimal i_dbID)
    {
        pm_objDS = new DS_V_HAN_SU_DUNG();
        pm_strTableName = c_TableName;
        IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
        v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
        SqlCommand v_cmdSQL;
        v_cmdSQL = v_objMkCmd.getSelectCmd();
        this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
        pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
    }
    #endregion
}
}
