///************************************************
/// Generated by: DungNT
/// Date: 31/03/2014 02:44:38
/// Goal: Create User Service Class for GD_DON_VI_TINH_THUOC
///************************************************
/// <summary>
/// Create User Service Class for GD_DON_VI_TINH_THUOC
/// </summary>

using System;
using BKI_QLHT.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLHT.US{

public class US_GD_DON_VI_TINH_THUOC : US_Object
{
	private const string c_TableName = "GD_DON_VI_TINH_THUOC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_DON_VI"] = value;
		}
	}

	public bool IsMA_DON_VINull() 
	{
		return pm_objDR.IsNull("MA_DON_VI");
	}

	public void SetMA_DON_VINull() {
		pm_objDR["MA_DON_VI"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_AP_DUNG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_AP_DUNG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_AP_DUNG"] = value;
		}
	}

	public bool IsNGAY_AP_DUNGNull()
	{
		return pm_objDR.IsNull("NGAY_AP_DUNG");
	}

	public void SetNGAY_AP_DUNGNull()
	{
		pm_objDR["NGAY_AP_DUNG"] = System.Convert.DBNull;
	}

	public decimal dcID_TRANG_THAI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TRANG_THAI"] = value;
		}
	}

	public bool IsID_TRANG_THAINull()	{
		return pm_objDR.IsNull("ID_TRANG_THAI");
	}

	public void SetID_TRANG_THAINull() {
		pm_objDR["ID_TRANG_THAI"] = System.Convert.DBNull;
	}

	public decimal dcID_NGUOI_THEM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_THEM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGUOI_THEM"] = value;
		}
	}

	public bool IsID_NGUOI_THEMNull()	{
		return pm_objDR.IsNull("ID_NGUOI_THEM");
	}

	public void SetID_NGUOI_THEMNull() {
		pm_objDR["ID_NGUOI_THEM"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_CHA 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_CHA", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_CHA"] = value;
		}
	}

	public bool IsID_DON_VI_CHANull()	{
		return pm_objDR.IsNull("ID_DON_VI_CHA");
	}

	public void SetID_DON_VI_CHANull() {
		pm_objDR["ID_DON_VI_CHA"] = System.Convert.DBNull;
	}

	public decimal dcQUY_DOI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "QUY_DOI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["QUY_DOI"] = value;
		}
	}

	public bool IsQUY_DOINull()	{
		return pm_objDR.IsNull("QUY_DOI");
	}

	public void SetQUY_DOINull() {
		pm_objDR["QUY_DOI"] = System.Convert.DBNull;
	}

	public decimal dcID_NHOM_DON_VI_TINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHOM_DON_VI_TINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHOM_DON_VI_TINH"] = value;
		}
	}

	public bool IsID_NHOM_DON_VI_TINHNull()	{
		return pm_objDR.IsNull("ID_NHOM_DON_VI_TINH");
	}

	public void SetID_NHOM_DON_VI_TINHNull() {
		pm_objDR["ID_NHOM_DON_VI_TINH"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_DON_VI_TINH_THUOC() 
	{
		pm_objDS = new DS_GD_DON_VI_TINH_THUOC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_DON_VI_TINH_THUOC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_DON_VI_TINH_THUOC(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_DON_VI_TINH_THUOC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion





    public void FillDatasetbyIdLoaiDonVi(DS_GD_DON_VI_TINH_THUOC op_ds, decimal ip_id_loaidonvi)
    {
        CStoredProc v_stored_proc = new CStoredProc("pr_DANH_MUC_DON_VI_TINH_fill_dataset_byIDLoaiDonVi");
        v_stored_proc.addDecimalInputParam("@id_loai_tu_dien", ip_id_loaidonvi);
        v_stored_proc.fillDataSetByCommand(this, op_ds);
    }
}
}
