///************************************************
/// Generated by: HuyTD
/// Date: 01/05/2014 10:58:18
/// Goal: Create User Service Class for GD_DON_VI_TINH_THUOC
///************************************************
/// <summary>
/// Create User Service Class for GD_DON_VI_TINH_THUOC
/// </summary>

using System;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;


namespace BKI_QLHT.US{

public class US_GD_DON_VI_TINH_THUOC : US_Object
{
	private const string c_TableName = "GD_DON_VI_TINH_THUOC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_CHA 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_CHA", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_CHA"] = value;
		}
	}

	public bool IsID_DON_VI_CHANull()	{
		return pm_objDR.IsNull("ID_DON_VI_CHA");
	}

	public void SetID_DON_VI_CHANull() {
		pm_objDR["ID_DON_VI_CHA"] = System.Convert.DBNull;
	}

	public decimal dcQUY_DOI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "QUY_DOI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["QUY_DOI"] = value;
		}
	}

	public bool IsQUY_DOINull()	{
		return pm_objDR.IsNull("QUY_DOI");
	}

	public void SetQUY_DOINull() {
		pm_objDR["QUY_DOI"] = System.Convert.DBNull;
	}

	public decimal dcID_NHOM_DON_VI_TINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHOM_DON_VI_TINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHOM_DON_VI_TINH"] = value;
		}
	}

	public bool IsID_NHOM_DON_VI_TINHNull()	{
		return pm_objDR.IsNull("ID_NHOM_DON_VI_TINH");
	}

	public void SetID_NHOM_DON_VI_TINHNull() {
		pm_objDR["ID_NHOM_DON_VI_TINH"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_DON_VI_TINH_THUOC() 
	{
		pm_objDS = new DS_GD_DON_VI_TINH_THUOC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_DON_VI_TINH_THUOC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_DON_VI_TINH_THUOC(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_DON_VI_TINH_THUOC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
