///************************************************
/// Generated by: TuNA
/// Date: 13-05-2014 02:55:08
/// Goal: Create User Service Class for V_BAO_CAO_DOANH_THU_TONG_HOP
///************************************************
/// <summary>
/// Create User Service Class for V_BAO_CAO_DOANH_THU_TONG_HOP
/// </summary>

using System;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;


namespace BKI_QLHT.US
{

public class US_V_BAO_CAO_DOANH_THU_TONG_HOP : US_Object
{
	private const string c_TableName = "V_BAO_CAO_DOANH_THU_TONG_HOP";
#region "Public Properties"
	public string strMA_GIAO_DICH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_GIAO_DICH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_GIAO_DICH"] = value;
		}
	}

	public bool IsMA_GIAO_DICHNull() 
	{
		return pm_objDR.IsNull("MA_GIAO_DICH");
	}

	public void SetMA_GIAO_DICHNull() {
		pm_objDR["MA_GIAO_DICH"] = System.Convert.DBNull;
	}

	public string strNGAY_GIAO_DICH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGAY_GIAO_DICH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGAY_GIAO_DICH"] = value;
		}
	}

	public bool IsNGAY_GIAO_DICHNull() 
	{
		return pm_objDR.IsNull("NGAY_GIAO_DICH");
	}

	public void SetNGAY_GIAO_DICHNull() {
		pm_objDR["NGAY_GIAO_DICH"] = System.Convert.DBNull;
	}

	public string strTEN_NHOM_KH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NHOM_KH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NHOM_KH"] = value;
		}
	}

	public bool IsTEN_NHOM_KHNull() 
	{
		return pm_objDR.IsNull("TEN_NHOM_KH");
	}

	public void SetTEN_NHOM_KHNull() {
		pm_objDR["TEN_NHOM_KH"] = System.Convert.DBNull;
	}

	public string strMA_KHACH_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_KHACH_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_KHACH_HANG"] = value;
		}
	}

	public bool IsMA_KHACH_HANGNull() 
	{
		return pm_objDR.IsNull("MA_KHACH_HANG");
	}

	public void SetMA_KHACH_HANGNull() {
		pm_objDR["MA_KHACH_HANG"] = System.Convert.DBNull;
	}

	public string strTEN_KHACH_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_KHACH_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_KHACH_HANG"] = value;
		}
	}

	public bool IsTEN_KHACH_HANGNull() 
	{
		return pm_objDR.IsNull("TEN_KHACH_HANG");
	}

	public void SetTEN_KHACH_HANGNull() {
		pm_objDR["TEN_KHACH_HANG"] = System.Convert.DBNull;
	}

	public string strTEN_BAC_SY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_BAC_SY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_BAC_SY"] = value;
		}
	}

	public bool IsTEN_BAC_SYNull() 
	{
		return pm_objDR.IsNull("TEN_BAC_SY");
	}

	public void SetTEN_BAC_SYNull() {
		pm_objDR["TEN_BAC_SY"] = System.Convert.DBNull;
	}

	public string strTEN_NHAN_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NHAN_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NHAN_VIEN"] = value;
		}
	}

	public bool IsTEN_NHAN_VIENNull() 
	{
		return pm_objDR.IsNull("TEN_NHAN_VIEN");
	}

	public void SetTEN_NHAN_VIENNull() {
		pm_objDR["TEN_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public string strTEN_NCC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NCC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NCC"] = value;
		}
	}

	public bool IsTEN_NCCNull() 
	{
		return pm_objDR.IsNull("TEN_NCC");
	}

	public void SetTEN_NCCNull() {
		pm_objDR["TEN_NCC"] = System.Convert.DBNull;
	}

	public string strTEN_NHOM_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NHOM_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NHOM_THUOC"] = value;
		}
	}

	public bool IsTEN_NHOM_THUOCNull() 
	{
		return pm_objDR.IsNull("TEN_NHOM_THUOC");
	}

	public void SetTEN_NHOM_THUOCNull() {
		pm_objDR["TEN_NHOM_THUOC"] = System.Convert.DBNull;
	}

	public string strTEN_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_THUOC"] = value;
		}
	}

	public bool IsTEN_THUOCNull() 
	{
		return pm_objDR.IsNull("TEN_THUOC");
	}

	public void SetTEN_THUOCNull() {
		pm_objDR["TEN_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG_BAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG_BAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG_BAN"] = value;
		}
	}

	public bool IsSO_LUONG_BANNull()	{
		return pm_objDR.IsNull("SO_LUONG_BAN");
	}

	public void SetSO_LUONG_BANNull() {
		pm_objDR["SO_LUONG_BAN"] = System.Convert.DBNull;
	}

	public string strDON_VI_TINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DON_VI_TINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DON_VI_TINH"] = value;
		}
	}

	public bool IsDON_VI_TINHNull() 
	{
		return pm_objDR.IsNull("DON_VI_TINH");
	}

	public void SetDON_VI_TINHNull() {
		pm_objDR["DON_VI_TINH"] = System.Convert.DBNull;
	}

	public decimal dcGIA_BAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA_BAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA_BAN"] = value;
		}
	}

	public bool IsGIA_BANNull()	{
		return pm_objDR.IsNull("GIA_BAN");
	}

	public void SetGIA_BANNull() {
		pm_objDR["GIA_BAN"] = System.Convert.DBNull;
	}

	public decimal dcTI_LE_CHIET_KHAU_NHOM_KH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TI_LE_CHIET_KHAU_NHOM_KH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TI_LE_CHIET_KHAU_NHOM_KH"] = value;
		}
	}

	public bool IsTI_LE_CHIET_KHAU_NHOM_KHNull()	{
		return pm_objDR.IsNull("TI_LE_CHIET_KHAU_NHOM_KH");
	}

	public void SetTI_LE_CHIET_KHAU_NHOM_KHNull() {
		pm_objDR["TI_LE_CHIET_KHAU_NHOM_KH"] = System.Convert.DBNull;
	}

	public string strHAN_SU_DUNG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HAN_SU_DUNG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HAN_SU_DUNG"] = value;
		}
	}

	public bool IsHAN_SU_DUNGNull() 
	{
		return pm_objDR.IsNull("HAN_SU_DUNG");
	}

	public void SetHAN_SU_DUNGNull() {
		pm_objDR["HAN_SU_DUNG"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_BAO_CAO_DOANH_THU_TONG_HOP() 
	{
		pm_objDS = new DS_V_BAO_CAO_DOANH_THU_TONG_HOP();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_BAO_CAO_DOANH_THU_TONG_HOP(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_BAO_CAO_DOANH_THU_TONG_HOP(decimal i_dbID) 
	{
		pm_objDS = new DS_V_BAO_CAO_DOANH_THU_TONG_HOP();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
