///************************************************
/// Generated by: VinhNQ
/// Date: 02/05/2014 05:35:46
/// Goal: Create User Service Class for V_HAN_SU_DUNG
///************************************************
/// <summary>
/// Create User Service Class for V_HAN_SU_DUNG
/// </summary>

using System;
using BKI_QLHT.DS;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;


namespace BKI_QLHT{

public class US_V_HAN_SU_DUNG : US_Object
{
	private const string c_TableName = "V_HAN_SU_DUNG";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcSO_DU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_DU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_DU"] = value;
		}
	}

	public bool IsSO_DUNull()	{
		return pm_objDR.IsNull("SO_DU");
	}

	public void SetSO_DUNull() {
		pm_objDR["SO_DU"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_THUOC"] = value;
		}
	}

	public bool IsID_DON_VI_THUOCNull()	{
		return pm_objDR.IsNull("ID_DON_VI_THUOC");
	}

	public void SetID_DON_VI_THUOCNull() {
		pm_objDR["ID_DON_VI_THUOC"] = System.Convert.DBNull;
	}

	public DateTime datHAN_SU_DUNG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "HAN_SU_DUNG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["HAN_SU_DUNG"] = value;
		}
	}

	public bool IsHAN_SU_DUNGNull()
	{
		return pm_objDR.IsNull("HAN_SU_DUNG");
	}

	public void SetHAN_SU_DUNGNull()
	{
		pm_objDR["HAN_SU_DUNG"] = System.Convert.DBNull;
	}

	public string strTEN_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_THUOC"] = value;
		}
	}

	public bool IsTEN_THUOCNull() 
	{
		return pm_objDR.IsNull("TEN_THUOC");
	}

	public void SetTEN_THUOCNull() {
		pm_objDR["TEN_THUOC"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public string strMOI_NHAT_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MOI_NHAT_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MOI_NHAT_YN"] = value;
		}
	}

	public bool IsMOI_NHAT_YNNull() 
	{
		return pm_objDR.IsNull("MOI_NHAT_YN");
	}

	public void SetMOI_NHAT_YNNull() {
		pm_objDR["MOI_NHAT_YN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_HAN_SU_DUNG() 
	{
		pm_objDS = new DS_V_HAN_SU_DUNG();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_HAN_SU_DUNG(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_HAN_SU_DUNG(decimal i_dbID) 
	{
		pm_objDS = new DS_V_HAN_SU_DUNG();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
