///************************************************
/// Generated by: HuyTD
/// Date: 07/05/2014 05:58:32
/// Goal: Create User Service Class for V_GD_GIAO_DICH_DETAIL
///************************************************
/// <summary>
/// Create User Service Class for V_GD_GIAO_DICH_DETAIL
/// </summary>

using System;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;


namespace BKI_QLHT.US{

public class US_V_GD_GIAO_DICH_DETAIL : US_Object
{
	private const string c_TableName = "V_GD_GIAO_DICH_DETAIL";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_GIAO_DICH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GIAO_DICH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GIAO_DICH"] = value;
		}
	}

	public bool IsID_GIAO_DICHNull()	{
		return pm_objDR.IsNull("ID_GIAO_DICH");
	}

	public void SetID_GIAO_DICHNull() {
		pm_objDR["ID_GIAO_DICH"] = System.Convert.DBNull;
	}

	public decimal dcID_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_THUOC"] = value;
		}
	}

	public bool IsID_THUOCNull()	{
		return pm_objDR.IsNull("ID_THUOC");
	}

	public void SetID_THUOCNull() {
		pm_objDR["ID_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_THUOC"] = value;
		}
	}

	public bool IsID_DON_VI_THUOCNull()	{
		return pm_objDR.IsNull("ID_DON_VI_THUOC");
	}

	public void SetID_DON_VI_THUOCNull() {
		pm_objDR["ID_DON_VI_THUOC"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG_NHAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG_NHAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG_NHAP"] = value;
		}
	}

	public bool IsSO_LUONG_NHAPNull()	{
		return pm_objDR.IsNull("SO_LUONG_NHAP");
	}

	public void SetSO_LUONG_NHAPNull() {
		pm_objDR["SO_LUONG_NHAP"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG_BAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG_BAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG_BAN"] = value;
		}
	}

	public bool IsSO_LUONG_BANNull()	{
		return pm_objDR.IsNull("SO_LUONG_BAN");
	}

	public void SetSO_LUONG_BANNull() {
		pm_objDR["SO_LUONG_BAN"] = System.Convert.DBNull;
	}

	public decimal dcID_NHA_CUNG_CAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHA_CUNG_CAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHA_CUNG_CAP"] = value;
		}
	}

	public bool IsID_NHA_CUNG_CAPNull()	{
		return pm_objDR.IsNull("ID_NHA_CUNG_CAP");
	}

	public void SetID_NHA_CUNG_CAPNull() {
		pm_objDR["ID_NHA_CUNG_CAP"] = System.Convert.DBNull;
	}

	public decimal dcID_NUOC_SX 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NUOC_SX", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NUOC_SX"] = value;
		}
	}

	public bool IsID_NUOC_SXNull()	{
		return pm_objDR.IsNull("ID_NUOC_SX");
	}

	public void SetID_NUOC_SXNull() {
		pm_objDR["ID_NUOC_SX"] = System.Convert.DBNull;
	}

	public decimal dcID_HANG_SX 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_HANG_SX", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_HANG_SX"] = value;
		}
	}

	public bool IsID_HANG_SXNull()	{
		return pm_objDR.IsNull("ID_HANG_SX");
	}

	public void SetID_HANG_SXNull() {
		pm_objDR["ID_HANG_SX"] = System.Convert.DBNull;
	}

	public DateTime datHAN_SU_DUNG
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "HAN_SU_DUNG", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["HAN_SU_DUNG"] = value;
		}
	}

	public bool IsHAN_SU_DUNGNull()
	{
		return pm_objDR.IsNull("HAN_SU_DUNG");
	}

	public void SetHAN_SU_DUNGNull()
	{
		pm_objDR["HAN_SU_DUNG"] = System.Convert.DBNull;
	}

	public decimal dcGIA_NHAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA_NHAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA_NHAP"] = value;
		}
	}

	public bool IsGIA_NHAPNull()	{
		return pm_objDR.IsNull("GIA_NHAP");
	}

	public void SetGIA_NHAPNull() {
		pm_objDR["GIA_NHAP"] = System.Convert.DBNull;
	}

	public decimal dcGIA_BAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA_BAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA_BAN"] = value;
		}
	}

	public bool IsGIA_BANNull()	{
		return pm_objDR.IsNull("GIA_BAN");
	}

	public void SetGIA_BANNull() {
		pm_objDR["GIA_BAN"] = System.Convert.DBNull;
	}

	public decimal dcID_LO_THUOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LO_THUOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LO_THUOC"] = value;
		}
	}

	public bool IsID_LO_THUOCNull()	{
		return pm_objDR.IsNull("ID_LO_THUOC");
	}

	public void SetID_LO_THUOCNull() {
		pm_objDR["ID_LO_THUOC"] = System.Convert.DBNull;
	}

	public string strTEN_THUOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_THUOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_THUOC"] = value;
		}
	}

	public bool IsTEN_THUOCNull() 
	{
		return pm_objDR.IsNull("TEN_THUOC");
	}

	public void SetTEN_THUOCNull() {
		pm_objDR["TEN_THUOC"] = System.Convert.DBNull;
	}

	public string strDUONG_DUNG_DANG_DUNG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DUONG_DUNG_DANG_DUNG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DUONG_DUNG_DANG_DUNG"] = value;
		}
	}

	public bool IsDUONG_DUNG_DANG_DUNGNull() 
	{
		return pm_objDR.IsNull("DUONG_DUNG_DANG_DUNG");
	}

	public void SetDUONG_DUNG_DANG_DUNGNull() {
		pm_objDR["DUONG_DUNG_DANG_DUNG"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_CHA 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_CHA", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_CHA"] = value;
		}
	}

	public bool IsID_DON_VI_CHANull()	{
		return pm_objDR.IsNull("ID_DON_VI_CHA");
	}

	public void SetID_DON_VI_CHANull() {
		pm_objDR["ID_DON_VI_CHA"] = System.Convert.DBNull;
	}

	public decimal dcQUY_DOI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "QUY_DOI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["QUY_DOI"] = value;
		}
	}

	public bool IsQUY_DOINull()	{
		return pm_objDR.IsNull("QUY_DOI");
	}

	public void SetQUY_DOINull() {
		pm_objDR["QUY_DOI"] = System.Convert.DBNull;
	}

	public decimal dcGIA_BAN_GD_GIA_BAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GIA_BAN_GD_GIA_BAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GIA_BAN_GD_GIA_BAN"] = value;
		}
	}

	public bool IsGIA_BAN_GD_GIA_BANNull()	{
		return pm_objDR.IsNull("GIA_BAN_GD_GIA_BAN");
	}

	public void SetGIA_BAN_GD_GIA_BANNull() {
		pm_objDR["GIA_BAN_GD_GIA_BAN"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_TINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_TINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_TINH"] = value;
		}
	}

	public bool IsID_DON_VI_TINHNull()	{
		return pm_objDR.IsNull("ID_DON_VI_TINH");
	}

	public void SetID_DON_VI_TINHNull() {
		pm_objDR["ID_DON_VI_TINH"] = System.Convert.DBNull;
	}

	public decimal dcID_GD_GIAO_DICH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GD_GIAO_DICH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GD_GIAO_DICH"] = value;
		}
	}

	public bool IsID_GD_GIAO_DICHNull()	{
		return pm_objDR.IsNull("ID_GD_GIAO_DICH");
	}

	public void SetID_GD_GIAO_DICHNull() {
		pm_objDR["ID_GD_GIAO_DICH"] = System.Convert.DBNull;
	}

	public string strMA_GIAO_DICH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_GIAO_DICH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_GIAO_DICH"] = value;
		}
	}

	public bool IsMA_GIAO_DICHNull() 
	{
		return pm_objDR.IsNull("MA_GIAO_DICH");
	}

	public void SetMA_GIAO_DICHNull() {
		pm_objDR["MA_GIAO_DICH"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_GIAO_DICH
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_GIAO_DICH", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_GIAO_DICH"] = value;
		}
	}

	public bool IsNGAY_GIAO_DICHNull()
	{
		return pm_objDR.IsNull("NGAY_GIAO_DICH");
	}

	public void SetNGAY_GIAO_DICHNull()
	{
		pm_objDR["NGAY_GIAO_DICH"] = System.Convert.DBNull;
	}

	public decimal dcID_NGUOI_THUC_HIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_THUC_HIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGUOI_THUC_HIEN"] = value;
		}
	}

	public bool IsID_NGUOI_THUC_HIENNull()	{
		return pm_objDR.IsNull("ID_NGUOI_THUC_HIEN");
	}

	public void SetID_NGUOI_THUC_HIENNull() {
		pm_objDR["ID_NGUOI_THUC_HIEN"] = System.Convert.DBNull;
	}

	public decimal dcID_KHACH_HANG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_KHACH_HANG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_KHACH_HANG"] = value;
		}
	}

	public bool IsID_KHACH_HANGNull()	{
		return pm_objDR.IsNull("ID_KHACH_HANG");
	}

	public void SetID_KHACH_HANGNull() {
		pm_objDR["ID_KHACH_HANG"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_GIAO_DICH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_GIAO_DICH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_GIAO_DICH"] = value;
		}
	}

	public bool IsID_LOAI_GIAO_DICHNull()	{
		return pm_objDR.IsNull("ID_LOAI_GIAO_DICH");
	}

	public void SetID_LOAI_GIAO_DICHNull() {
		pm_objDR["ID_LOAI_GIAO_DICH"] = System.Convert.DBNull;
	}

	public decimal dcTI_LE_CHIET_KHAU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TI_LE_CHIET_KHAU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TI_LE_CHIET_KHAU"] = value;
		}
	}

	public bool IsTI_LE_CHIET_KHAUNull()	{
		return pm_objDR.IsNull("TI_LE_CHIET_KHAU");
	}

	public void SetTI_LE_CHIET_KHAUNull() {
		pm_objDR["TI_LE_CHIET_KHAU"] = System.Convert.DBNull;
	}

	public decimal dcID_DM_KHACH_HANG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DM_KHACH_HANG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DM_KHACH_HANG"] = value;
		}
	}

	public bool IsID_DM_KHACH_HANGNull()	{
		return pm_objDR.IsNull("ID_DM_KHACH_HANG");
	}

	public void SetID_DM_KHACH_HANGNull() {
		pm_objDR["ID_DM_KHACH_HANG"] = System.Convert.DBNull;
	}

	public string strTEN_KHACH_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_KHACH_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_KHACH_HANG"] = value;
		}
	}

	public bool IsTEN_KHACH_HANGNull() 
	{
		return pm_objDR.IsNull("TEN_KHACH_HANG");
	}

	public void SetTEN_KHACH_HANGNull() {
		pm_objDR["TEN_KHACH_HANG"] = System.Convert.DBNull;
	}

	public string strSDT_KH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SDT_KH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SDT_KH"] = value;
		}
	}

	public bool IsSDT_KHNull() 
	{
		return pm_objDR.IsNull("SDT_KH");
	}

	public void SetSDT_KHNull() {
		pm_objDR["SDT_KH"] = System.Convert.DBNull;
	}

	public string strDIA_CHI_KH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI_KH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI_KH"] = value;
		}
	}

	public bool IsDIA_CHI_KHNull() 
	{
		return pm_objDR.IsNull("DIA_CHI_KH");
	}

	public void SetDIA_CHI_KHNull() {
		pm_objDR["DIA_CHI_KH"] = System.Convert.DBNull;
	}

	public decimal dcID_DV_KINH_DOANH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DV_KINH_DOANH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DV_KINH_DOANH"] = value;
		}
	}

	public bool IsID_DV_KINH_DOANHNull()	{
		return pm_objDR.IsNull("ID_DV_KINH_DOANH");
	}

	public void SetID_DV_KINH_DOANHNull() {
		pm_objDR["ID_DV_KINH_DOANH"] = System.Convert.DBNull;
	}

	public string strTEN_DAY_DU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DAY_DU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DAY_DU"] = value;
		}
	}

	public bool IsTEN_DAY_DUNull() 
	{
		return pm_objDR.IsNull("TEN_DAY_DU");
	}

	public void SetTEN_DAY_DUNull() {
		pm_objDR["TEN_DAY_DU"] = System.Convert.DBNull;
	}

	public string strDIA_CHI_DV 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI_DV", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI_DV"] = value;
		}
	}

	public bool IsDIA_CHI_DVNull() 
	{
		return pm_objDR.IsNull("DIA_CHI_DV");
	}

	public void SetDIA_CHI_DVNull() {
		pm_objDR["DIA_CHI_DV"] = System.Convert.DBNull;
	}

	public string strSD 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SD", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SD"] = value;
		}
	}

	public bool IsSDNull() 
	{
		return pm_objDR.IsNull("SD");
	}

	public void SetSDNull() {
		pm_objDR["SD"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_GD_GIAO_DICH_DETAIL() 
	{
		pm_objDS = new DS_V_GD_GIAO_DICH_DETAIL();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_GD_GIAO_DICH_DETAIL(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_GD_GIAO_DICH_DETAIL(decimal i_dbID) 
	{
		pm_objDS = new DS_V_GD_GIAO_DICH_DETAIL();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
