///************************************************
/// Generated by: TuNA
/// Date: 23-05-2014 03:04:06
/// Goal: Create User Service Class for V_BC_DOANH_THU_BAC_SY
///************************************************
/// <summary>
/// Create User Service Class for V_BC_DOANH_THU_BAC_SY
/// </summary>

using System;
using BKI_QLHT;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using BKI_QLHT.DS;
using BKI_QLHT.DS.CDBNames;

namespace BKI_QLHT.US
{

public class US_V_BC_DOANH_THU_BAC_SY : US_Object
{
	private const string c_TableName = "V_BC_DOANH_THU_BAC_SY";

#region "Public Properties"
	public string strTEN_BAC_SY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_BAC_SY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_BAC_SY"] = value;
		}
	}

	public bool IsTEN_BAC_SYNull() 
	{
		return pm_objDR.IsNull("TEN_BAC_SY");
	}

	public void SetTEN_BAC_SYNull() {
		pm_objDR["TEN_BAC_SY"] = System.Convert.DBNull;
	}

	public string strNGAY_GIAO_DICH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGAY_GIAO_DICH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGAY_GIAO_DICH"] = value;
		}
	}

	public bool IsNGAY_GIAO_DICHNull() 
	{
		return pm_objDR.IsNull("NGAY_GIAO_DICH");
	}

	public void SetNGAY_GIAO_DICHNull() {
		pm_objDR["NGAY_GIAO_DICH"] = System.Convert.DBNull;
	}

	public decimal dcDOANH_THU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DOANH_THU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DOANH_THU"] = value;
		}
	}

	public bool IsDOANH_THUNull()	{
		return pm_objDR.IsNull("DOANH_THU");
	}

	public void SetDOANH_THUNull() {
		pm_objDR["DOANH_THU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
    public void FillDatasetSearch(BKI_QLHT.DS.V_BC_DOANH_THU_BAC_SY op_ds_bc_da, string i_str_tu_khoa, DateTime i_dat_ngay_bd, DateTime i_dat_ngay_kt)
    {
        CStoredProc v_sp = new CStoredProc("pr_V_BC_DOANH_THU_BAC_SY_search");
        v_sp.addNVarcharInputParam("@STR_SEARCH", i_str_tu_khoa);
        v_sp.addDatetimeInputParam("@DAT_BD", i_dat_ngay_bd);
        v_sp.addDatetimeInputParam("@DAT_KT", i_dat_ngay_kt);
        v_sp.fillDataSetByCommand(this, op_ds_bc_da);
    }
	public US_V_BC_DOANH_THU_BAC_SY() 
	{
		pm_objDS = new BKI_QLHT.DS.V_BC_DOANH_THU_BAC_SY();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_BC_DOANH_THU_BAC_SY(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_BC_DOANH_THU_BAC_SY(decimal i_dbID) 
	{
		pm_objDS = new BKI_QLHT.DS.V_BC_DOANH_THU_BAC_SY();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}	
}
